"use client";

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    dashboard: "Dashboard",
    employees: "Employees",
    finances: "Finances & Sales",
    leaves: "Leave Requests",
    reports: "Reports",
    logout: "Logout",
    welcome: "Welcome back",
    add_employee: "Add Employee",
    search_placeholder: "Search by name, title, or ID...",
    present_today: "Present Today",
    absent_today: "Absent Today",
    currently_in: "Currently Checked In",
    total_hours: "Total Hours Today",
    quick_access: "Quick Access",
    employee_list: "Employee List",
    daily_finances: "Daily Finances",
    personal_info: "Personal Information",
    attendance: "Attendance",
    documents: "Documents",
    medical_reports: "Medical Reports",
    penalties: "Penalties & Notes",
    salary_summary: "Salary Summary",
    hourly_rate: "Hourly Rate",
    hours_this_month: "Hours This Month",
    calculated_salary: "Calculated Salary",
    save: "Save",
    cancel: "Cancel",
    submit: "Submit",
    loading: "Loading...",
    sign_in: "Sign In",
    username: "Username",
    password: "Password",
    back_to_employees: "Back to Employees",
    full_name: "Full Name",
    job_title: "Job Title",
    phone_number: "Phone Number",
    national_id: "National ID / Iqama",
    address: "Address",
    hiring_date: "Hiring Date",
    account_details: "Account Details",
    status: "Status",
    actions: "Actions",
    view_profile: "View Profile",
    no_employees: "No employees found.",
    today_snapshot: "Today's snapshot",
    sales: "Sales",
    expenses: "Expenses",
    update_sales: "Update Sales",
    add_expense: "Add Expense",
    upload_invoice: "Upload Invoice",
    report_type: "Report Type",
    generate_report: "Generate Report",
    export_print: "Export / Print",
    attendance_system: "Attendance System",
    check_in: "Check In",
    check_out: "Check Out",
    manual_check_in: "Manual Check In",
    currently_working: "Currently Working",
    offline: "Offline",
    not_checked_in: "Not currently checked in",
    recent_history: "Recent History",
    date: "Date",
    in_progress: "In Progress",
    no_records: "No records yet",
    checked_in_at: "Checked in at",
    daily_sales: "Daily Sales",
    daily_expenses: "Daily Expenses",
    net_position: "Net Position",
    manage_expenses: "Manage Expenses",
    expense_description: "Expense description...",
    amount: "Amount",
    add: "Add",
    no_expenses: "No expenses today",
    recent_invoices: "Recent Invoices",
    upload: "Upload",
    view: "View",
    category: "Category",
    file: "File",
    register: "Register",
    back_to_login: "Back to Login",
    sun: "Sun",
    mon: "Mon",
    tue: "Tue",
    wed: "Wed",
    thu: "Thu",
    fri: "Fri",
    sat: "Sat",
    id_photo: "ID/Iqama Photo",
    error_username_length: "Username must be at least 8 characters",
    error_password_length: "Password must be at least 8 characters",
    error_min_letters: "Must contain at least 2 letters",
    error_id_photo_required: "National ID photo is required",
    register_title: "Create Employee Account",
    already_have_account: "Already have an account? Sign in",
    id_upload_help: "Please upload a clear photo of your ID",
    health_certificate: "Health Certificate",
    health_upload_help: "Optional health certificate photo",
    leave_management: "Leave Management",
    leave_requests_desc: "Review and approve employee leave requests",
    payroll_management: "Accounting & Payroll",
    base_salary: "Base Salary",
    bonuses: "Bonuses",
    deductions: "Deductions",
    advances: "Advances",
    net_salary: "Net Salary",
    finalize_payment: "Finalize & Pay",
    payroll_month: "Payroll Month",
    payroll_year: "Payroll Year",
    calculate: "Calculate",
    hours_unit: "Hours",
    status_paid: "Paid",
    status_pending: "Pending",
    rejected: "Rejected",
    request_leave: "Request Leave",
    leave_type: "Type",
    vacation_leave: "Vacation Leave",
    sick_leave: "Sick Leave",
    emergency_leave: "Emergency Leave",
    period: "Period",
    start_date: "Start Date",
    end_date: "End Date",
    no_history: "No history found",
    upload_report: "Upload Report",
    documents_records: "Documents & Records",
    upload_document: "Upload Document",
    no_documents: "No documents uploaded yet",
    uploading_document: "Uploading document...",
    uploaded: "Uploaded",
    penalties_notes: "Penalties & Notes",
    add_record: "Add Record",
    no_records_logged: "No warnings or notes logged",
    warning: "Warning",
    penalty: "Penalty",
    note: "Note",
    description: "Description",
    details_placeholder: "Details about this record...",
    save_record: "Save Record",
    per_hour: "per hour",
    salary_help_text: "Based on current month's work",
    delete: "Delete",
    are_you_sure: "Are you sure?",
    delete_success: "Deleted successfully!",
    employee_dashboard: "My Dashboard",
    present: "Present",
    vacant: "No Records",
    today: "Today",
    detailed_records: "Detailed Attendance Records",
    monthly_attendance_summary: "Monthly Activity Overview",
    no_records_for_period: "No records found for this period",
    monthly_attendance_sheet: "Monthly Attendance Sheet",
    day: "Day",
    invoice_number: "Invoice Number",
    monthly_finance: "Monthly Finance",
    net_profit: "Net Profit",
    total_sales: "Total Sales",
    total_expenses: "Total Expenses",
    add_sale: "Add Sale",
    edit_sale: "Edit Sale",
    details: "Details",
    finance_reports: "Finance Reports",
    current_month: "Current Month",
    previous_month: "Previous Month",
    next_month: "Next Month",
    selected_period: "Selected Period",
    rent: "Rent",
    salary: "Salary",
    payroll: "Payroll",
    settle_account: "Settle Account",
    payment_history: "Payment History",
    settlement_details: "Settlement Details",
    due_amount: "Amount to be paid",
    not_settled: "Not settled",
    active: "Active",
    search: "Search",
  },
  ar: {
    dashboard: "لوحة التحكم",
    employees: "الموظفين",
    finances: "المالية والمبيعات",
    leaves: "طلبات الإجازة",
    reports: "التقارير",
    logout: "تسجيل الخروج",
    welcome: "مرحباً بك",
    add_employee: "إضافة موظف",
    search_placeholder: "ابحث بالاسم، الوظيفة، أو الرقم...",
    present_today: "الحضور اليوم",
    absent_today: "الغياب اليوم",
    currently_in: "المسجلين حالياً",
    total_hours: "إجمالي الساعات اليوم",
    quick_access: "وصول سريع",
    employee_list: "قائمة الموظفين",
    daily_finances: "المالية اليومية",
    personal_info: "المعلومات الشخصية",
    attendance: "الحضور والانصراف",
    documents: "المستندات",
    medical_reports: "التقارير الطبية",
    penalties: "الجزاءات والملاحظات",
    salary_summary: "ملخص الراتب",
    hourly_rate: "أجر الساعة",
    hours_this_month: "ساعات الشهر",
    calculated_salary: "الراتب المحتسب",
    save: "حفظ",
    cancel: "إلغاء",
    submit: "إرسال",
    loading: "جاري التحميل...",
    sign_in: "تسجيل الدخول",
    username: "اسم المستخدم",
    password: "كلمة المرور",
    back_to_employees: "العودة للموظفين",
    full_name: "الاسم الكامل",
    job_title: "المسمى الوظيفي",
    phone_number: "رقم الهاتف",
    national_id: "الهوية / الإقامة",
    address: "العنوان",
    hiring_date: "تاريخ التوظيف",
    account_details: "تفاصيل الحساب",
    status: "الحالة",
    actions: "إجراءات",
    view_profile: "عرض الملف",
    no_employees: "لم يتم العثور على موظفين.",
    today_snapshot: "إحصائيات اليوم",
    sales: "المبيعات",
    expenses: "المصاريف",
    update_sales: "تحديث المبيعات",
    add_expense: "إضافة مصروف",
    upload_invoice: "رفع فاتورة",
    report_type: "نوع التقرير",
    generate_report: "إنشاء تقرير",
    export_print: "تصدير / طباعة",
    attendance_system: "نظام التحضير",
    check_in: "تسجيل دخول",
    check_out: "تسجيل خروج",
    manual_check_in: "حضور يدوي",
    currently_working: "يعمل حالياً",
    offline: "غير متصل",
    not_checked_in: "لم يتم تسجيل الحضور حالياً",
    recent_history: "السجل الأخير",
    date: "التاريخ",
    in_progress: "قيد التنفيذ",
    no_records: "لا توجد سجلات",
    checked_in_at: "تم الدخول في",
    daily_sales: "المبيعات اليومية",
    daily_expenses: "المصاريف اليومية",
    net_position: "صافي الربح",
    manage_expenses: "إدارة المصاريف",
    expense_description: "وصف المصروف...",
    amount: "المبلغ",
    add: "إضافة",
    no_expenses: "لا توجد مصاريف اليوم",
    recent_invoices: "الفواتير الأخيرة",
    upload: "رفع",
    view: "عرض",
    category: "الفئة",
    file: "الملف",
    register: "تسجيل جديد",
    register_title: "إنشاء حساب موظف",
    already_have_account: "لديك حساب بالفعل؟ سجل دخولك",
    id_photo: "صورة الهوية / الإقامة",
    id_upload_help: "يرجى رفع صورة واضحة للهوية",
    health_certificate: "الشهادة الصحية",
    health_upload_help: "صورة الشهادة الصحية (اختياري)",
    leave_management: "إدارة الإجازات",
    leave_requests_desc: "مراجعة واعتماد طلبات إجازات الموظفين",
    payroll_management: "المحاسبة والرواتب",
    base_salary: "الراتب الأساسي",
    bonuses: "المكافآت",
    deductions: "الخصومات والغرامات",
    advances: "السلف والقروض",
    net_salary: "صافي الراتب",
    finalize_payment: "اعتماد وصرف",
    payroll_month: "الشهر المالي",
    payroll_year: "السنة المالية",
    calculate: "حساب",
    hours_unit: "ساعة",
    status_paid: "تم الصرف",
    status_pending: "قيد الانتظار",
    rejected: "مرفوض",
    request_leave: "طلب إجازة",
    leave_type: "النوع",
    vacation_leave: "إجازة اعتيادية",
    sick_leave: "إجازة مرضية",
    emergency_leave: "إجازة اضطرارية",
    period: "الفترة",
    start_date: "تاريخ البدء",
    end_date: "تاريخ الانتهاء",
    no_history: "لا يوجد سجل",
    upload_report: "رفع تقرير",
    documents_records: "المستندات والجداول",
    upload_document: "رفع مستند",
    no_documents: "لم يتم رفع مستندات بعد",
    uploading_document: "جاري رفع المستند...",
    uploaded: "تم الرفع في",
    penalties_notes: "الجزاءات والملاحظات",
    add_record: "إضافة سجل",
    no_records_logged: "لا توجد تنبيهات أو ملاحظات مسجلة",
    warning: "تنبيه",
    penalty: "جزاء",
    note: "ملاحظة",
    description: "الوصف",
    details_placeholder: "تفاصيل السجل...",
    save_record: "حفظ السجل",
    per_hour: "في الساعة",
    salary_help_text: "بناءً على عمل الشهر الحالي",
    active: "نشط",
    search: "بحث",
    delete: "حذف",
    are_you_sure: "هل أنت متأكد؟",
    delete_success: "تم الحذف بنجاح!",
    employee_dashboard: "لوحتي",
    present: "حاضر",
    vacant: "لا يوجد",
    today: "اليوم",
    detailed_records: "سجل الحضور التفصيلي",
    monthly_attendance_summary: "ملخص النشاط الشهري",
    no_records_for_period: "لا توجد سجلات لهذه الفترة",
    monthly_attendance_sheet: "مسير الحضور الشهري",
    day: "اليوم",
    invoice_number: "رقم الفاتورة",
    monthly_finance: "المالية الشهرية",
    net_profit: "صافي الربح",
    total_sales: "إجمالي المبيعات",
    total_expenses: "إجمالي المصروفات",
    add_sale: "إضافة مبيعات",
    edit_sale: "تعديل المبيعات",
    details: "التفاصيل",
    finance_reports: "تقارير المالية",
    current_month: "الشهر الحالي",
    previous_month: "الشهر السابق",
    next_month: "الشهر التالي",
    selected_period: "الفترة المختارة",
    rent: "إيجار",
    salary: "رواتب",
    payroll: "المسيرات / الرواتب",
    settle_account: "تصفية الحساب",
    payment_history: "سجل المدفوعات",
    remaining_balance: "الرصيد المتبقي",
    total_earned: "إجمالي المستحقات",
    total_paid: "إجمالي ما تم صرفه",
    settle_success: "تمت تصفية الحساب بنجاح",
    other: "أخرى",
    financial_overview: "نظرة مالية شاملة",
    pending_dues: "المستحقات المعلقة",
    hours_total: "إجمالي الساعات",
    settlement_details: "تفاصيل التصفية النهائية",
    due_amount: "المبلغ المطلوب دفعه",
    not_settled: "غير مدفوع",
    back_to_login: "العودة لتسجيل الدخول",
    sun: "الأحد",
    mon: "الأثنين",
    tue: "الثلاثاء",
    wed: "الأربعاء",
    thu: "الخميس",
    fri: "الجمعة",
    sat: "السبت",
    error_username_length: "اسم المستخدم يجب أن يكون ٨ أحرف على الأقل",
    error_password_length: "كلمة المرور يجب أن تكون ٨ أحرف على الأقل",
    error_min_letters: "يجب أن يحتوي على حرفين على الأقل",
    error_id_photo_required: "صورة الهوية مطلوبة",
    full_name_required: "الاسم بالكامل مطلوب",
    work_salary: "العمل والراتب",
    account_credentials: "بيانات تسجيل الدخول",
    create_employee: "إنشاء حساب موظف",
    saved: "تم الحفظ!",
    required: "مطلوب",
    employee: "الموظف",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const saved = localStorage.getItem('lang') as Language;
    if (saved) {
      setLanguageState(saved);
      document.documentElement.dir = saved === 'ar' ? 'rtl' : 'ltr';
      document.documentElement.lang = saved;
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('lang', lang);
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
